name: CI
on:
  push:
    branches: 
      - qa
jobs:
  build:

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_NON_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_NON_PROD }}
      NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY: AIzaSyBZYw_akBPQy2hFoLj4ACrr3zLeA9R6RVU
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: dk-learning-nonprod.firebaseapp.com
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: dk-learning-nonprod
      NEXT_PUBLIC_DOMAIN: https://learning-qa.dk.com
      FIREBASE_PRIVATE_KEY: ${{ secrets.SECRET_FIREBASE_PRIVATE_KEY }}
      FIREBASE_CLIENT_EMAIL: firebase-adminsdk-j2uus@dk-learning-nonprod.iam.gserviceaccount.com
      NEXT_PUBLIC_GTM_PROPERTY: GTM-K3F8RX8
      NEXT_PUBLIC_GTAG_PROPERTY: UA-209946048-1
      NEXT_PUBLIC_COOKIE_SECURE: true
      NEXT_PUBLIC_CMS_API_KEY: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImdjbXMtbWFpbi1wcm9kdWN0aW9uIn0.eyJ2ZXJzaW9uIjozLCJpYXQiOjE2MzM0NDU4MzAsImF1ZCI6WyJodHRwczovL2FwaS1ldS1jZW50cmFsLTEuZ3JhcGhjbXMuY29tL3YyL2NrdThkdHlpbjNvMjIwMXhoNTF0bmQ5emovbWFzdGVyIiwiaHR0cHM6Ly9tYW5hZ2VtZW50LW5leHQuZ3JhcGhjbXMuY29tIl0sImlzcyI6Imh0dHBzOi8vbWFuYWdlbWVudC5ncmFwaGNtcy5jb20vIiwic3ViIjoiNzkwMGFiYjAtMmEyMy00NjE4LWJlMTUtZWRjN2YyYmVkZTYyIiwianRpIjoiY2t1ZTdoMWVpN2Z6MTAxemViOWZ0aHFlOCJ9.ePRfNnE2Zla0FqbYBE_Eq6UDyhSO2MwPuiDpWWMT4lgNwbvi-jyNiyojSjlrKo0i4jw8rfQKKsyPbICvLgeMG64aQ5SpbOmXK-Ok28nnV88nOuarO5pUvamC8li4qQBKIu-Jk9Y33bhwAUbloHDbxg6J8JFDG9R7KPiV1gVL10PFKgp4NofVmcDz9_LE_SHtaeKftBW0l9wSenbZeF0rAG_l6u6T5rMhzp_SwXt-BQg07GdJuWqZtgxNakXuq2omN0aq5BMExx20J8ZwcaOi1nysb9u34Rfw541mB8lo1rlbiAw6auUKUg0IWMiLVnGRBEDPhixk8s1cgPoKsiHCCR4Y4dl-96wMkl6BnOiI10bmztAWIQ3_4C3Xg3_lmYtXmUmP7hccg07evkhwIs9LT6K_01x_Q-qor8IyfOTcY4AQQ2_YZGS_MALheaBid62GZieuslcH-A4pVPAwx_4kHm9hK_U_bB3ugOLd_cfs7bfIO_jMDtERu0xusmkJd-B7LgBPmfW7ByuXZg0wLY8TDRlPmlP9Wadc1tH8y5jam7w1VGEgKAXbeJtUZkgE-2TF3R5EqnaNkw6zCiSZ6M3yowI2Pa9LRbir0-7iWdmbR1Tfri5IY3wVWR5M-nxsKS024kdzmEYhQkP9Pak6oVSx3ihZpMDPhAaLhvXPq5sTuRg
      NEXT_PUBLIC_CMS_ENDPOINT: https://api-eu-central-1.graphcms.com/v2/cku8dtyin3o2201xh51tnd9zj/master
      NEXT_PUBLIC_ALGOLIA_APP_ID: 2EY1E9WGMG
      NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY: d9b57cb726f229a8062ecec2fd2e4889
      DK_CORE_API_URL: https://1lfnaioer9.execute-api.eu-west-1.amazonaws.com/dev
      DK_CORE_API_KEY: QECCQWOQQf5YHrSx2hCkf1YF66MnwPBe1z1yEBQ8
      DEPLOYMENT_BUCKET_NAME: rn8tl7-m6nznaz
      CLOUDFRONT_DISTRIBUTION_ID: E13YWBNLSFS5F2

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install NPM dependencies
        run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NON_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NON_PROD }}
          aws-region: us-east-1

      - name: Download `.serverless` state from S3
        run: aws s3 sync s3://dk-learning-nonprod-serverless-artifacts/qa/.serverless .serverless

      - name: Deploy Next.js app
        run: npx serverless@2.72.2

      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless s3://dk-learning-nonprod-serverless-artifacts/qa/.serverless
